version: '2'
services:
  kernel-module-mcu-loader:
    build:
      context: .
      dockerfile: Dockerfile.template
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'

